packages:
  - 'vscode-plugin'
  - 'apps/*'
  - 'libs/**'
  - '../extends-react'
  - '../extends-antd'
  - '../extends-hono'
  - '../extends-hono/libs/vite-config-lib'
  - '../extends-mcp/libs/mcpserver'
  - '../packagecli/packagecli-mcpserver'
  - '../packagecli/packagecli-lib'
  - '../remote-runtimeobj/webrtcsignaling'
  - '../remote-runtimeobj/public'
  - '../remote-runtimeobj/vscode-plugin-proxy'
  - '../extends-ssh/ubuntu-lib'
  - '../extends-vite'
  - '../extends-zustand/libs/zustand-lib'
