packages:
  - 'vscode-plugin'
  - 'apps/*'
  - 'libs/**'
  - '../extends-react'
  - '../extends-antd'
  - '../extends-hono'
  - '../extends-hono/libs/vite.config'
  - '../extends-ssh'
  - '../extends-vite'
  - '../extends-zustand'
