packages:
  - 'vscode-plugin'
  - 'apps/*'
  - 'libs/**'
  - '../extends-react'
  - '../extends-antd'
  - '../extends-hono'
  - '../extends-hono/libs/vite.config'
  - '../extends-hono/libs/mcpServer'
  - '../extends-hono/libs/windows-named-pipe'
  - '../create-todo-cli/src'
  - '../create-todo-cli/mcpCreate'
  - '../remote-runtimeobj/abstractBase'
  - '../remote-runtimeobj/vscode-plugin-proxy'
  - '../remote-runtimeobj/webrtcsignaling'
  - '../extends-ssh/ubuntu-lib'
  - '../extends-vite'
  - '../extends-zustand'
